// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Convert swagger.yaml to markdown",
    "title": "swagger2markdown",
    "version": "1.0.0",
    "x-direktiv-meta": {
      "category": "Documents",
      "container": "direktiv/swagger2markdown",
      "issues": "https://github.com/direktiv-apps/swagger2markdown/issues",
      "license": "[Apache-2.0](https://www.apache.org/licenses/LICENSE-2.0)",
      "long-description": "Converts a swagger file into a markdown file based on the provided template. The swagger file as well as the template have to be provided as files.",
      "maintainer": "[direktiv.io](https://www.direktiv.io) ",
      "url": "https://github.com/direktiv-apps/swagger2markdown"
    }
  },
  "paths": {
    "/": {
      "post": {
        "parameters": [
          {
            "type": "string",
            "description": "direktiv action id is an UUID. \nFor development it can be set to 'development'\n",
            "name": "Direktiv-ActionID",
            "in": "header"
          },
          {
            "type": "string",
            "description": "direktiv temp dir is the working directory for that request\nFor development it can be set to e.g. '/tmp'\n",
            "name": "Direktiv-TempDir",
            "in": "header"
          },
          {
            "name": "body",
            "in": "body",
            "schema": {
              "type": "object",
              "required": [
                "template"
              ],
              "properties": {
                "swagger": {
                  "description": "Path of the swagger YAML file to process.",
                  "type": "string",
                  "default": "swagger.yaml",
                  "example": "swagger.yaml"
                },
                "template": {
                  "description": "Path of the template to use for markdown generation.",
                  "type": "string",
                  "example": "template.tmpl"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "nice greeting",
            "schema": {
              "type": "object",
              "properties": {
                "readme": {
                  "description": "Base64 encoded markdown file.",
                  "type": "string",
                  "example": "CgoKIyBzd2FnZ2V...gfCAgfAoKCg=="
                }
              }
            },
            "examples": {
              "basic": {
                "readme": "2CgoKIyBzd2FnZ2V...gfCAgfAoKCg=="
              }
            }
          },
          "default": {
            "description": "generic error response",
            "schema": {
              "$ref": "#/definitions/error"
            },
            "headers": {
              "Direktiv-ErrorCode": {
                "type": "string"
              },
              "Direktiv-ErrorMessage": {
                "type": "string"
              }
            }
          }
        },
        "x-direktiv": {
          "cmds": [
            {
              "action": "exec",
              "exec": "mkdir -p templates/markdown"
            },
            {
              "action": "exec",
              "exec": "mv {{ .Template }} templates/markdown"
            },
            {
              "action": "exec",
              "exec": "swagger generate markdown -f {{ default \"swagger.yaml\" .Swagger }} --output=out/instance/readme.md --template-dir=templates/ --with-flatten=full"
            },
            {
              "action": "exec",
              "exec": "base64 -w0 out/instance/readme.md",
              "print": false
            }
          ],
          "output": "{\n  \"readme\": \"{{ index (index . 3) \"result\" }}\"\n}\n"
        },
        "x-direktiv-errors": {
          "io.direktiv.command.error": "Command execution failed",
          "io.direktiv.output.error": "Template error for output generation of the service",
          "io.direktiv.ri.error": "Can not create information object from request"
        },
        "x-direktiv-examples": [
          {
            "content": "- id: req\n     type: action\n     action:\n       function: swagger2markdown\n       input:\n        swagger: swagger.yaml",
            "title": "Basic"
          }
        ],
        "x-direktiv-function": "functions:\n  - id: swagger2markdown\n    image: direktiv/swagger2markdown\n    type: knative-workflow"
      },
      "delete": {
        "parameters": [
          {
            "type": "string",
            "description": "On cancel Direktiv sends a DELETE request to\nthe action with id in the header\n",
            "name": "Direktiv-ActionID",
            "in": "header"
          }
        ],
        "responses": {
          "200": {
            "description": ""
          }
        },
        "x-direktiv": {
          "cancel": "echo 'cancel {{ .DirektivActionID }}'"
        }
      }
    }
  },
  "definitions": {
    "direktivFile": {
      "type": "object",
      "x-go-type": {
        "import": {
          "package": "github.com/direktiv/apps/go/pkg/apps"
        },
        "type": "DirektivFile"
      }
    },
    "error": {
      "type": "object",
      "required": [
        "errorCode",
        "errorMessage"
      ],
      "properties": {
        "errorCode": {
          "type": "string"
        },
        "errorMessage": {
          "type": "string"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Convert swagger.yaml to markdown",
    "title": "swagger2markdown",
    "version": "1.0.0",
    "x-direktiv-meta": {
      "category": "Documents",
      "container": "direktiv/swagger2markdown",
      "issues": "https://github.com/direktiv-apps/swagger2markdown/issues",
      "license": "[Apache-2.0](https://www.apache.org/licenses/LICENSE-2.0)",
      "long-description": "Converts a swagger file into a markdown file based on the provided template. The swagger file as well as the template have to be provided as files.",
      "maintainer": "[direktiv.io](https://www.direktiv.io) ",
      "url": "https://github.com/direktiv-apps/swagger2markdown"
    }
  },
  "paths": {
    "/": {
      "post": {
        "parameters": [
          {
            "type": "string",
            "description": "direktiv action id is an UUID. \nFor development it can be set to 'development'\n",
            "name": "Direktiv-ActionID",
            "in": "header"
          },
          {
            "type": "string",
            "description": "direktiv temp dir is the working directory for that request\nFor development it can be set to e.g. '/tmp'\n",
            "name": "Direktiv-TempDir",
            "in": "header"
          },
          {
            "name": "body",
            "in": "body",
            "schema": {
              "type": "object",
              "required": [
                "template"
              ],
              "properties": {
                "swagger": {
                  "description": "Path of the swagger YAML file to process.",
                  "type": "string",
                  "default": "swagger.yaml",
                  "example": "swagger.yaml"
                },
                "template": {
                  "description": "Path of the template to use for markdown generation.",
                  "type": "string",
                  "example": "template.tmpl"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "nice greeting",
            "schema": {
              "type": "object",
              "properties": {
                "readme": {
                  "description": "Base64 encoded markdown file.",
                  "type": "string",
                  "example": "CgoKIyBzd2FnZ2V...gfCAgfAoKCg=="
                }
              }
            },
            "examples": {
              "basic": {
                "readme": "2CgoKIyBzd2FnZ2V...gfCAgfAoKCg=="
              }
            }
          },
          "default": {
            "description": "generic error response",
            "schema": {
              "$ref": "#/definitions/error"
            },
            "headers": {
              "Direktiv-ErrorCode": {
                "type": "string"
              },
              "Direktiv-ErrorMessage": {
                "type": "string"
              }
            }
          }
        },
        "x-direktiv": {
          "cmds": [
            {
              "action": "exec",
              "exec": "mkdir -p templates/markdown"
            },
            {
              "action": "exec",
              "exec": "mv {{ .Template }} templates/markdown"
            },
            {
              "action": "exec",
              "exec": "swagger generate markdown -f {{ default \"swagger.yaml\" .Swagger }} --output=out/instance/readme.md --template-dir=templates/ --with-flatten=full"
            },
            {
              "action": "exec",
              "exec": "base64 -w0 out/instance/readme.md",
              "print": false
            }
          ],
          "output": "{\n  \"readme\": \"{{ index (index . 3) \"result\" }}\"\n}\n"
        },
        "x-direktiv-errors": {
          "io.direktiv.command.error": "Command execution failed",
          "io.direktiv.output.error": "Template error for output generation of the service",
          "io.direktiv.ri.error": "Can not create information object from request"
        },
        "x-direktiv-examples": [
          {
            "content": "- id: req\n     type: action\n     action:\n       function: swagger2markdown\n       input:\n        swagger: swagger.yaml",
            "title": "Basic"
          }
        ],
        "x-direktiv-function": "functions:\n  - id: swagger2markdown\n    image: direktiv/swagger2markdown\n    type: knative-workflow"
      },
      "delete": {
        "parameters": [
          {
            "type": "string",
            "description": "On cancel Direktiv sends a DELETE request to\nthe action with id in the header\n",
            "name": "Direktiv-ActionID",
            "in": "header"
          }
        ],
        "responses": {
          "200": {
            "description": ""
          }
        },
        "x-direktiv": {
          "cancel": "echo 'cancel {{ .DirektivActionID }}'"
        }
      }
    }
  },
  "definitions": {
    "direktivFile": {
      "type": "object",
      "x-go-type": {
        "import": {
          "package": "github.com/direktiv/apps/go/pkg/apps"
        },
        "type": "DirektivFile"
      }
    },
    "error": {
      "type": "object",
      "required": [
        "errorCode",
        "errorMessage"
      ],
      "properties": {
        "errorCode": {
          "type": "string"
        },
        "errorMessage": {
          "type": "string"
        }
      }
    }
  }
}`))
}
